# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 27 Mar 2014 12:12:43 +0000
*	@ALL	0
*	@user	8
favorites	@user	1
sidebar	@user	1
