<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: gnap
 * Date: Wed, 18 Jun 2014 21:59:03 +0300
 */

$conf['title'] = 'GNaP';
$conf['template'] = 'gnap';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['useheading'] = '1';
$conf['hidepages'] = 'sidebar';
$conf['useacl'] = 1;
$conf['authtype'] = 'authplain';
$conf['superuser'] = 'gnap,@GNaP_Admins';
$conf['disableactions'] = 'register,resendpwd,profile,profile_delete';
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'dotnet@infrabel.be';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['sepchar'] = '-';
$conf['gzip_output'] = 1;
$conf['plugin']['authad']['account_suffix'] = '@infrabel.be';
$conf['plugin']['authad']['base_dn'] = 'DC=infrabel,DC=be';
$conf['plugin']['authad']['domain_controllers'] = '<Insert comma separated FQDN list of domain controllers here>';
$conf['plugin']['authad']['sso'] = 1;
$conf['plugin']['authad']['admin_username'] = 'SYS-GNaP';
$conf['plugin']['authad']['admin_password'] = '<Insert password here>';
$conf['plugin']['dw2pdf']['usecache'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['indexmenu']['show_sort'] = 1;

// end auto-generated content
